<a href="https://colab.research.google.com/github/abdumahkamovelshod/numpy/blob/main/Copy_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [3]:
import numpy as np
np.__version__

'1.25.2'

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [4]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [5]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [6]:
np.array([1,2,3,4]).size
np.array([1,2,3,4]).itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [7]:
np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [8]:
a=np.zeros(12)
a[5]=1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [9]:
np.arange(20,60)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [10]:
a=np.arange(5)
a[::-1]

array([4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [11]:
np.arange(12,21).reshape(3,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [12]:
a=np.array([3, 7, 0, 0, 9, 0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [13]:
np.random.random((2,2,2))


array([[[0.91683299, 0.94408094],
        [0.29532307, 0.26156638]],

       [[0.14143721, 0.82478326],
        [0.58921957, 0.91406532]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [14]:
a=np.random.random((9,9))
a.min()
a.max()

0.9836172978069886

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [15]:
0 * np.nan # 0
np.nan == np.nan# True
np.inf > np.nan# True
np.nan - np.nan #0
np.nan in set([np.nan]) #True
0.7 == 7 * 0.1#Falae

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [16]:
a=np.random.random((6,3))
b=np.random.random((3,4))
np.dot(a,b)

array([[0.98376336, 0.70627106, 0.64114343, 0.34340948],
       [0.87100809, 0.48941517, 0.48243298, 0.17185463],
       [0.5850871 , 0.54891637, 0.47176806, 0.33427734],
       [0.4627583 , 0.3197091 , 0.3006216 , 0.15270881],
       [0.5823873 , 0.77577901, 0.68407053, 0.5902194 ],
       [0.93422036, 1.06141676, 0.89309386, 0.72523941]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [17]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [18]:
a=np.array([1,2])
b=np.array([4,5])
a>b
a>=b
a<b
a<=b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [19]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


<ipython-input-19-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-19-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-19-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [20]:
a=np.arange(1,10)
b=np.arange(5,15)
np.intersect1d(a,b)

array([5, 6, 7, 8, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [21]:
#np.floor
a=np.random.randn(5)
k=[]
for i in a:
  if i>0:
   k.append(np.floor(i))
print(k)

[0.0, 0.0, 2.0, 1.0]


In [22]:
#np.astype
b=np.random.randn(10)
b=b.astype(dtype=np.int64)
b

array([-1,  0,  0, -1,  0,  0,  0,  1,  0,  1])

In [23]:
k=np.random.randn(5)
np.trunc(k)

array([-0.,  0., -0., -0., -0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [24]:
np.arange(0.2,2,0.20).reshape(3,3)

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [25]:
a=np.random.randn(10)
a.sort()
a

array([-0.59283547, -0.46691801, -0.34730319, -0.1824361 , -0.17093875,
       -0.04346792,  0.0512216 ,  0.3551164 ,  0.43974354,  0.77421946])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [26]:
a=np.random.randn(5)
b=np.random.randn(5)
np.array_equal(a,b)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [27]:
np.dot(np.random.randn(6,3),np.random.randn(3,4))

array([[ 1.06856527, -1.38743835,  0.37986605,  1.07953627],
       [ 0.52111766, -3.15498344,  3.07471668, -0.21557678],
       [-0.21294824,  0.95021243, -0.89413754,  0.06111418],
       [-0.60848523, -0.40962581,  1.01086009, -0.58611513],
       [-1.07440046,  1.99782538, -0.82423399, -1.49396665],
       [-1.56794571,  0.9767814 ,  0.92565494, -2.46258094]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [28]:
a=np.random.randn(5)
a.sort()
a[-1]=0
print(a)

[-0.81536352 -0.70272276 -0.624317   -0.11247571  0.        ]


#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [29]:
y=np.datetime64('2024-02-21')
t=np.datetime64('2024-02-22')
to=np.datetime64('2024-02-23')
print(y,t,to)

2024-02-21 2024-02-22 2024-02-23


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [35]:
a = np.datetime64('2016-01-01')
b = np.datetime64('2016-02-01')

ab = np.arange(a, b, dtype='datetime64[D]')
print(ab)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [49]:
a=np.random.rand(5)
a
print(np.floor(a))
a=a.astype(dtype=int64)
print(a)
print(np.trunc(a))

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[0. 0. 0. 0. 0.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [50]:
a=np.arange(3)
b=np.arange(4)
np.add.reduce(a)
np.add.reduce(b)

6

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [58]:
a=np.arange(1,6)
c=[0,0,0]
b=[]
for i in a:
  b.append(i)
  if i!=5:
   b.extend(c)
print(b)



[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [60]:
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
b = [a[i:i+4] for i in range(len(a)-3)]
print(b)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [81]:
a=np.arange(5)
b=np.arange(5)
c=np.concatenate((a,b))
np.unique(c)

array([0, 1, 2, 3, 4])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`